apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-service
spec:
  # The PDB is configured to require at least 1 pod to be available at all times, which helps maintain service availability during voluntary disruptions 
  # (e.g., node maintenance or scaling events). This ensures that the api-service can continue to serve requests even when some pods are temporarily unavailable.
  minAvailable: 1
  selector:
    matchLabels:
      app: api-service
