apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: api-service
    newName: hamza94/staging-api-service
    newTag: "staging-latest"

patches:
  - target:
      kind: Deployment
      name: api-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

  - target:
      kind: HorizontalPodAutoscaler
      name: api-service
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2
      - op: replace
        path: /spec/maxReplicas
        value: 6
