# This file is part of the Kubernetes production overlay configuration for the api-service deployment.
# It defines a Kustomization resource that pulls in the base configuration and applies production-specific patches
# to the Deployment and HorizontalPodAutoscaler resources. The production overlay uses a different Docker image
# and tag, increases the number of replicas, and adjusts the CPU resource requests and limits for
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources from base are pulled in unchanged, then production-specific patches are applied on top.
resources:
  - ../../base

# The production overlay uses a different Docker image and tag, increases the number of replicas, and adjusts the CPU resource requests and limits for the api-service deployment.
images:
  - name: api-service
    newName: hamza94/production-api-service
    newTag: "1.0.0"

# Patches are applied to the Deployment and HorizontalPodAutoscaler resources to customize their behavior for the production environment.
patches:
  - target:
      kind: Deployment
      name: api-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 4
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"

# Patches are applied to the HorizontalPodAutoscaler resource to adjust the minimum and maximum number of replicas for the api-service deployment in the production environment.
  - target:
      kind: HorizontalPodAutoscaler
      name: api-service
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 4
      - op: replace
        path: /spec/maxReplicas
        value: 20
